// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8lVoi5i1dWWbR57yE87m9zWt1LDVJArY',
    appId: '1:904203359576:web:77f9dd7d6949212be0c12d',
    messagingSenderId: '904203359576',
    projectId: 'fahasa-replica',
    authDomain: 'fahasa-replica.firebaseapp.com',
    databaseURL:
        'https://fahasa-replica-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fahasa-replica.appspot.com',
    measurementId: 'G-NT18P6202T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBCY1LllQJYEUJR3VLyJ4Gm1L_fszw8Zc',
    appId: '1:904203359576:android:9724d71bb53baaade0c12d',
    messagingSenderId: '904203359576',
    projectId: 'fahasa-replica',
    databaseURL:
        'https://fahasa-replica-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fahasa-replica.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByvk27k3dmhCZlMdkhI_MIt8IGKlJeQ-o',
    appId: '1:904203359576:ios:74a917ebbf73d2d8e0c12d',
    messagingSenderId: '904203359576',
    projectId: 'fahasa-replica',
    databaseURL:
        'https://fahasa-replica-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fahasa-replica.appspot.com',
    iosClientId:
        '904203359576-kupot8d0rdil4dbb2ksnahbpmgjpkehj.apps.googleusercontent.com',
    iosBundleId: 'com.example.fahasaApp',
  );
}
